- id: pre-commit-conventional-commits
  name: Commit Message Checker (Conventional Commits)
  entry: commit-msg.sh
  language: script
  description: Checks commit message for Conventional Commits formatting
  always_run: true
  stages: [commit-msg]
