repos:
  - repo: local
    hooks:
      - id: pre-commit-conventional-commits
        name: Commit Message Checker (Conventional Commits)
        entry: commit-msg.sh
        language: script
        stages: [commit-msg]
